FFSRC := \
	libavcodec/aac_ac3_parser.c \
	libavcodec/aac_parser.c \
	libavcodec/aacadtsdec.c \
	libavcodec/aacdec.c \
	libavcodec/aacps.c \
	libavcodec/aacpsdsp.c \
	libavcodec/aacsbr.c \
	libavcodec/aactab.c \
	libavcodec/ac3tab.c \
	libavcodec/allcodecs.c \
	libavcodec/audioconvert.c \
	libavcodec/avfft.c \
	libavcodec/avpacket.c \
	libavcodec/bitstream.c \
	libavcodec/bitstream_filter.c \
	libavcodec/cabac.c \
	libavcodec/dct.c \
	libavcodec/dct32_fixed.c \
	libavcodec/dct32_float.c \
	libavcodec/dsputil.c \
	libavcodec/error_resilience.c \
	libavcodec/faanidct.c \
	libavcodec/fft_fixed.c \
	libavcodec/fft_float.c \
	libavcodec/fmtconvert.c \
	libavcodec/golomb.c \
	libavcodec/h264.c \
	libavcodec/h264_cabac.c \
	libavcodec/h264_cavlc.c \
	libavcodec/h264_direct.c \
	libavcodec/h264_loopfilter.c \
	libavcodec/h264_parser.c \
	libavcodec/h264_ps.c \
	libavcodec/h264_refs.c \
	libavcodec/h264_sei.c \
	libavcodec/h264dsp.c \
	libavcodec/h264idct.c \
	libavcodec/h264pred.c \
	libavcodec/imgconvert.c \
	libavcodec/inverse.c \
	libavcodec/jrevdct.c \
	libavcodec/kbdwin.c \
	libavcodec/mdct_fixed.c \
	libavcodec/mdct_float.c \
	libavcodec/mpeg4audio.c \
	libavcodec/mpegaudio.c \
	libavcodec/mpegaudio_parser.c \
	libavcodec/mpegaudiodata.c \
	libavcodec/mpegaudiodec_float.c \
	libavcodec/mpegaudiodecheader.c \
	libavcodec/mpegaudiodsp.c \
	libavcodec/mpegaudiodsp_fixed.c \
	libavcodec/mpegaudiodsp_float.c \
	libavcodec/mpegvideo.c \
	libavcodec/options.c \
	libavcodec/parser.c \
	libavcodec/raw.c \
	libavcodec/rawdec.c \
	libavcodec/rdft.c \
	libavcodec/resample.c \
	libavcodec/resample2.c \
	libavcodec/sbrdsp.c \
	libavcodec/simple_idct.c \
	libavcodec/sinewin.c \
	libavcodec/timecode.c \
	libavcodec/utils.c \
	libavformat/allformats.c \
	libavformat/avio.c \
	libavformat/aviobuf.c \
	libavformat/cutils.c \
	libavformat/file.c \
	libavformat/id3v1.c \
	libavformat/id3v2.c \
	libavformat/isom.c \
	libavformat/metadata.c \
	libavformat/mov.c \
	libavformat/mov_chan.c \
	libavformat/mp3dec.c \
	libavformat/options.c \
	libavformat/os_support.c \
	libavformat/riff.c \
	libavformat/sdp.c \
	libavformat/seek.c \
	libavformat/utils.c \
	libavutil/adler32.c \
	libavutil/aes.c \
	libavutil/audio_fifo.c \
	libavutil/audioconvert.c \
	libavutil/avstring.c \
	libavutil/base64.c \
	libavutil/bprint.c \
	libavutil/cpu.c \
	libavutil/crc.c \
	libavutil/des.c \
	libavutil/dict.c \
	libavutil/error.c \
	libavutil/eval.c \
	libavutil/fifo.c \
	libavutil/file.c \
	libavutil/imgutils.c \
	libavutil/intfloat_readwrite.c \
	libavutil/inverse.c \
	libavutil/lfg.c \
	libavutil/lls.c \
	libavutil/log.c \
	libavutil/lzo.c \
	libavutil/mathematics.c \
	libavutil/md5.c \
	libavutil/mem.c \
	libavutil/opt.c \
	libavutil/parseutils.c \
	libavutil/pixdesc.c \
	libavutil/random_seed.c \
	libavutil/rational.c \
	libavutil/rc4.c \
	libavutil/samplefmt.c \
	libavutil/sha.c \
	libavutil/timecode.c \
	libavutil/tree.c \
	libavutil/utils.c
